parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    MLD\SessionVisitsBundle\Controller\SessionVisitsController: ~
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones